# Generated by Django 3.2.4 on 2021-06-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('post', models.CharField(max_length=400)),
                ('commend', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
