# Generated by Django 3.2.4 on 2021-06-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='commend',
            new_name='comment',
        ),
    ]
